services:
  postgres:
    image: postgres:15.18-alpine3.22
    container_name: ux_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ux_network

  directus:
    image: directus/directus:11.17.0
    container_name: ux_directus
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/directus/uploads:/directus/uploads
      - ./data/directus/extensions:/directus/extensions
    ports:
      - "${DIRECTUS_PORT}:8055"
    networks:
      - ux_network

networks:
  ux_network:
    driver: bridge
